version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appelspro
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d appelspro"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@postgres:5432/appelspro
      - REDIS_URL=redis://redis:6379
      - OFFLINE_MODE=false
      - FEATURE_SOURCING=true
      - FEATURE_CRAWLER=true
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

  ml:
    build:
      context: .
      dockerfile: apps/ml/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - OFFLINE_MODE=false
      - BM25_ENABLED=true
      - EMBEDDINGS_ENABLED=false
    volumes:
      - .:/app
      - ./infra/data:/app/data

  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@postgres:5432/appelspro
      - REDIS_URL=redis://redis:6379
      - FEATURE_SOURCING=true
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

  ingestion:
    build:
      context: .
      dockerfile: apps/ingestion/Dockerfile
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@postgres:5432/appelspro
      - REDIS_URL=redis://redis:6379
      - RATE_LIMIT_GLOBAL_RPS=2
      - RATE_LIMIT_PER_DOMAIN_RPS=1
      - DOMAIN_WHITELIST="*.gouv.fr, *.insee.fr, *.cci.fr, *.pagesjaunes.fr, *.github.io, *.notion.site, *.wordpress.com"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
  redis_data: