
name: Deploy to Google Cloud Run

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  PROJECT_ID: secure-electron-471013-r0
  REGION: europe-west1
  SERVICE_NAME: swideal-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker
      run: gcloud auth configure-docker europe-west1-docker.pkg.dev

    - name: Build and Push Images
      run: |
        gcloud builds submit --config cloudbuild.yaml \
          --substitutions=_WEB_IMAGE="europe-west1-docker.pkg.dev/$PROJECT_ID/swideal/swideal-web:$GITHUB_SHA",_API_IMAGE="europe-west1-docker.pkg.dev/$PROJECT_ID/swideal/swideal-api:$GITHUB_SHA"

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image europe-west1-docker.pkg.dev/$PROJECT_ID/swideal/swideal-api:$GITHUB_SHA \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --port 8080 \
          --set-env-vars "NODE_ENV=production,GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" \
          --memory 1Gi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 10 \
          --timeout 300

    - name: Verify Deployment
      run: |
        SERVICE_URL=$(gcloud run services describe $SERVICE_NAME --region=$REGION --format="value(status.url)")
        echo "Service deployed at: $SERVICE_URL"
        curl -f $SERVICE_URL/api/health
